# Generated by Django 4.2 on 2023-04-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionnaire", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
