# Generated by Django 4.2 on 2023-05-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singhor_db", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="singhor",
            old_name="photo_auteur",
            new_name="photo_autheur",
        ),
    ]
