# Generated by Django 4.2 on 2023-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singhor_db", "0003_alter_singhor_photo_autheur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singhor",
            name="photo_autheur",
            field=models.ImageField(upload_to="images"),
        ),
    ]
